const appStyles = {
  container: {
    flex: 1,
    borderColor: 'yellow',
    paddingTop: 40, // safeareaview not working
    backgroundColor: '#5D2725',
    alignItems: 'center',
  },
  card: {
    paddingLeft: 20,
    fontSize: 36,
    fontWeight: 'bold',
    flex: 1,
    borderColor: '#4D3324',
    borderWidth: 3,
    minWidth: '80%',
    height: 50,
    maxHeight: 50,
    justifyContent: 'center',
    backgroundColor: '#FFF596',
    alignItems: 'center',
    borderRadius: 16,
    color: '#5D2725',
    flexDirection: 'row',
  },
  buttons: {
    marginTop: 5,
    paddingLeft: 20,
    fontSize: 36,
    fontWeight: 'bold',
    flex: 1,
    borderColor: '#4D3324',
    borderWidth: 2,
    minWidth: '80%',
    maxWidth: '80%',
    maxHeight: 60,
    margin: 5,
    backgroundColor: '#FFF596',
    borderRadius: 16,
    color: '#5D2725',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 15,
    elevation: 5,
  },
  ended: {
    paddingLeft: 20,
    fontSize: 36,
    fontWeight: 'bold',
    flex: 1,
    borderColor: '#4D3324',
    borderWidth: 2,
    maxHeight: 60,
    margin: 5,
    backgroundColor: '#696969',
    borderRadius: 16,
    color: '#000000',
  },
  text: {
    fontSize: 36,
    fontWeight: '600',
  },
  hpText: {
    // color: 'red',
    fontSize: 36,
    flexDirection: 'row',
    flex: 3,
  },
  heart: {
    fontSize: 36,
    flexDirection: 'row',
    flex: 1,
  },
};

export default appStyles;
